### ISSUE TITLE
fails in atom for some reason

### ISSUE THREAD

**Issue by wenzowski** [wenzowski/eslint-config-xo-meatier#3]
@quavmo

**Comment by gavmor** [comment]
What I see:

```
Error: xo-meatier: Configuration for rule "react/jsx-closing-bracket-location" is invalid: Value "0" no (or more than one) schemas match.

Referenced from: /Users/gavin/Workspace/floobits/.eslintrc
Error: xo-meatier:
    Configuration for rule "react/jsx-closing-bracket-location" is invalid:
    Value "0" no (or more than one) schemas match.
Referenced from: /Users/gavin/Workspace/floobits/.eslintrc
    at validateRuleOptions (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-validator.js:118:15)
    at /Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-validator.js:165:13
    at Array.forEach (native)
    at Object.validate (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-validator.js:164:35)
    at load (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-file.js:520:19)
    at /Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-file.js:388:36
    at Array.reduceRight (native)
    at applyExtends (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-file.js:365:28)
    at Object.load (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config/config-file.js:527:22)
    at loadConfig (/Users/gavin/Workspace/floobits/node_modules/eslint/lib/config.js:67:33)
```

**Comment by wenzowski** [comment]
I don't think we tried [atom-linter-xo](https://github.com/sindresorhus/atom-linter-xo) because I didn't include a link to that in the Readme. What eslint plugin were we trying to use?

I'm not sure why, but it doesn't look like we're picking up the eslint from the project's node_modules.

**Comment by wenzowski** [comment]
heh, and also because that rule definition is [simply wrong](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-closing-bracket-location.md)
